set_property PACKAGE_PIN C5 [get_ports key[0]]
set_property IOSTANDARD LVCMOS33 [get_ports key*]

set_property PACKAGE_PIN C4 [get_ports led[0]]
set_property PACKAGE_PIN L5 [get_ports led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led*]

set_property PACKAGE_PIN H11 [get_ports sys_clk]
set_property PACKAGE_PIN B6 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sys_*]

set_property PACKAGE_PIN N4 [get_ports uart_rx]
set_property PACKAGE_PIN P5 [get_ports uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports uart*]


create_clock -period 20.000 -name sys_clk_pin -waveform {0.000 10.0} -add [get_ports sys_clk]



set_property PACKAGE_PIN P4 [get_ports GPIO_1[0]]
set_property PACKAGE_PIN P3 [get_ports GPIO_1[1]]
set_property PACKAGE_PIN P2 [get_ports GPIO_1[2]]
set_property PACKAGE_PIN N1 [get_ports GPIO_1[3]]
set_property PACKAGE_PIN M5 [get_ports GPIO_1[4]]
set_property PACKAGE_PIN M4 [get_ports GPIO_1[5]]
set_property PACKAGE_PIN M3 [get_ports GPIO_1[6]]
set_property PACKAGE_PIN M2 [get_ports GPIO_1[7]]
set_property PACKAGE_PIN M1 [get_ports GPIO_1[8]]
set_property PACKAGE_PIN L1 [get_ports GPIO_1[9]]
set_property PACKAGE_PIN L3 [get_ports GPIO_1[10]]
set_property PACKAGE_PIN L2 [get_ports GPIO_1[11]]
set_property PACKAGE_PIN K4 [get_ports GPIO_1[12]]
set_property PACKAGE_PIN K3 [get_ports GPIO_1[13]]
set_property PACKAGE_PIN J4 [get_ports GPIO_1[14]]
set_property PACKAGE_PIN J3 [get_ports GPIO_1[15]]
set_property PACKAGE_PIN J2 [get_ports GPIO_1[16]]
set_property PACKAGE_PIN J1 [get_ports GPIO_1[17]]
set_property PACKAGE_PIN H3 [get_ports GPIO_1[18]]
set_property PACKAGE_PIN H4 [get_ports GPIO_1[19]]
set_property PACKAGE_PIN H1 [get_ports GPIO_1[20]]
set_property PACKAGE_PIN H2 [get_ports GPIO_1[21]]
set_property PACKAGE_PIN F4 [get_ports GPIO_1[22]]
set_property PACKAGE_PIN G4 [get_ports GPIO_1[23]]
set_property PACKAGE_PIN F3 [get_ports GPIO_1[24]]
set_property PACKAGE_PIN F2 [get_ports GPIO_1[25]]
set_property PACKAGE_PIN F1 [get_ports GPIO_1[26]]
set_property PACKAGE_PIN G1 [get_ports GPIO_1[27]]
set_property PACKAGE_PIN C1 [get_ports GPIO_1[28]]
set_property PACKAGE_PIN D1 [get_ports GPIO_1[29]]
set_property PACKAGE_PIN D2 [get_ports GPIO_1[30]]
set_property PACKAGE_PIN E2 [get_ports GPIO_1[31]]
set_property PACKAGE_PIN B2 [get_ports GPIO_1[32]]
set_property PACKAGE_PIN B1 [get_ports GPIO_1[33]]
set_property PACKAGE_PIN D4 [get_ports GPIO_1[34]]
set_property PACKAGE_PIN E4 [get_ports GPIO_1[35]]
set_property PACKAGE_PIN B3 [get_ports GPIO_1[36]]
set_property PACKAGE_PIN A2 [get_ports GPIO_1[37]]
set_property PACKAGE_PIN A4 [get_ports GPIO_1[38]]
set_property PACKAGE_PIN A3 [get_ports GPIO_1[39]]
set_property PACKAGE_PIN C3 [get_ports GPIO_1[40]]
set_property PACKAGE_PIN D3 [get_ports GPIO_1[41]]
set_property PACKAGE_PIN A5 [get_ports GPIO_1[42]]
set_property PACKAGE_PIN B5 [get_ports GPIO_1[43]]


set_property PACKAGE_PIN H12 [get_ports GPIO_2[0]]
set_property PACKAGE_PIN M10 [get_ports GPIO_2[1]]
set_property PACKAGE_PIN P11 [get_ports GPIO_2[2]]
set_property PACKAGE_PIN P10 [get_ports GPIO_2[3]]
set_property PACKAGE_PIN N11 [get_ports GPIO_2[4]]
set_property PACKAGE_PIN N10 [get_ports GPIO_2[5]]
set_property PACKAGE_PIN M12 [get_ports GPIO_2[6]]
set_property PACKAGE_PIN M11 [get_ports GPIO_2[7]]
set_property PACKAGE_PIN P13 [get_ports GPIO_2[8]]
set_property PACKAGE_PIN P12 [get_ports GPIO_2[9]]
set_property PACKAGE_PIN L12 [get_ports GPIO_2[10]]
set_property PACKAGE_PIN L13 [get_ports GPIO_2[11]]
set_property PACKAGE_PIN L14 [get_ports GPIO_2[12]]
set_property PACKAGE_PIN M13 [get_ports GPIO_2[13]]
set_property PACKAGE_PIN M14 [get_ports GPIO_2[14]]
set_property PACKAGE_PIN N14 [get_ports GPIO_2[15]]
set_property PACKAGE_PIN K12 [get_ports GPIO_2[16]]
set_property PACKAGE_PIN K11 [get_ports GPIO_2[17]]
set_property PACKAGE_PIN J11 [get_ports GPIO_2[18]]
set_property PACKAGE_PIN J12 [get_ports GPIO_2[19]]
set_property PACKAGE_PIN J13 [get_ports GPIO_2[20]]
set_property PACKAGE_PIN J14 [get_ports GPIO_2[21]]
set_property PACKAGE_PIN H13 [get_ports GPIO_2[22]]
set_property PACKAGE_PIN H14 [get_ports GPIO_2[23]]
set_property PACKAGE_PIN G11 [get_ports GPIO_2[24]]
set_property PACKAGE_PIN F11 [get_ports GPIO_2[25]]
set_property PACKAGE_PIN G14 [get_ports GPIO_2[26]]
set_property PACKAGE_PIN F14 [get_ports GPIO_2[27]]
set_property PACKAGE_PIN F13 [get_ports GPIO_2[28]]
set_property PACKAGE_PIN E13 [get_ports GPIO_2[29]]
set_property PACKAGE_PIN F12 [get_ports GPIO_2[30]]
set_property PACKAGE_PIN E12 [get_ports GPIO_2[31]]
set_property PACKAGE_PIN D14 [get_ports GPIO_2[32]]
set_property PACKAGE_PIN C14 [get_ports GPIO_2[33]]
set_property PACKAGE_PIN D13 [get_ports GPIO_2[34]]
set_property PACKAGE_PIN D12 [get_ports GPIO_2[35]]
set_property PACKAGE_PIN B14 [get_ports GPIO_2[36]]
set_property PACKAGE_PIN B13 [get_ports GPIO_2[37]]
set_property PACKAGE_PIN A13 [get_ports GPIO_2[38]]
set_property PACKAGE_PIN A12 [get_ports GPIO_2[39]]
set_property PACKAGE_PIN A10 [get_ports GPIO_2[40]]
set_property PACKAGE_PIN B10 [get_ports GPIO_2[41]]
set_property PACKAGE_PIN C12 [get_ports GPIO_2[42]]
set_property PACKAGE_PIN E11 [get_ports GPIO_2[43]]



set_property IOSTANDARD LVCMOS33 [get_ports GPIO*]






set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]